name: Build and Push Docker image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-alpine:${{ github.sha }} .
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.Xavier308 }}
          password: ${{ secrets.CR_PAT }}
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hello-alpine:${{ github.sha }}
